environment: dev

turboLogzUserApi: turbologz/turbo-logz-user-api:6
turboLogzApplicationsApi: turbologz/turbo-logz-applications-api:13
turboLogzGraphql: turbologz/turbo-logz-graphql:6
turboLogzUi: turbologz/turbo-logz-ui:2

serviceType: ClusterIP
ImagePullPolicy: Always

kafkaManager:
  username: admin
  password: admin
